//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//Signup
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

//Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";